
language: node_js
node_js:
  - '7'
script:
  - echo $NPMRC_TOKEN_CONTENT >> ~/.npmrc
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then npm publish; fi'
